config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)

  mount ActionCable.server => '/cable'

  devise_for :users

  resources :tours
	root 'tours#index'

  get '/tours_by_owner', to: 'tours#tours_by_owner', as: 'tours_by_owner'
  delete '/tours/:id/trip_leave/', to: 'tours#trip_leave', as: 'tours_trip_leave'
  post '/tours/subscribe', to: 'tours#subscribe', as: 'tours_subscribe'
  post '/tours/:id/kick', to: 'tours#kick_user', as: 'tour_kick'
  post '/tours/:id/unsubscribe', to: 'tours#unsubscribe', as: 'tours_unsubscribe'
  get '/contest', to: 'tours#contest', as: 'tours_contest'
  post '/new_contest_participant', to: 'tours#new_contest_participant'

  post '/tours/:id/idea', to: 'tours#post_idea', as: 'tours_new_idea'
  delete '/tours/:id/ideas/', to: 'tours#delete_idea', as: 'tours_delete_idea'

  post '/tours/:id/lock', to: 'tours#lock_tour', as: 'tours_lock'
  post '/tours/:id/unlock', to: 'tours#unlock_tour', as: 'tours_unlock'
  get '/contact_us', to: 'static_pages#contactus', as: 'contact_us'
  post '/static_pages/enquiry_contact_details', to: 'static_pages#enquiry_contact_details', as: 'enquiry_contact_details'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contactus
  end

  def enquiry_contact_details
    fullname= params[:full_name]
    email = params[:email]
    msg=params[:message]
    mobile_number= params[:number]
    UserMailer.enquiry_contact_details(fullname,email,msg,mobile_number).deliver_now!
    flash[:notice] = 'Thank you for contact us. We will update you soon..'
    redirect_to root_path
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contactus.html.erb
<div class="white-bg pad-block contact-wrap">
  <div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="contact-detail">
            </div>
        </div>
        <div class="col-sm-8">
            <h2 class="contact-title">Contact Form</h2>
            <div class="contact-form">
              <%= form_tag(enquiry_contact_details_path, {:method => :post,:id => :contact_form}) do %>
              <div class="form-group">
              <%= label_tag :Full_Name%>
               <%= text_field_tag :full_name, params[:full_name],class:"form-control", placeholder:"Full Name" %>
             </div>
             <!-- <div class="row">
               <div class="col-sm-6"> -->
             <div class="form-group">
             <%= label_tag :Email_Address%>
              <%= text_field_tag :email, params[:email],class:"form-control",type:'email', placeholder:"Email Address" %>
            </div>
          <!-- </div> -->
          <!-- <div class="col-sm-6">
            <div class="form-group">
            <%= label_tag :Phone_Number%>
             <%= text_field_tag :number, params[:number],class:"form-control", placeholder:"Phone Number" %>
           </div>
         </div> -->
       <!-- </div> -->

           <div class="form-group">
           <%= label_tag :Message%>
            <%= text_area_tag :message, params[:message],class:"form-control", placeholder:"Message" %>
          </div>
          <div class="text-center">
              <%= submit_tag "Send", :name => nil,class: "btn btn-default fill-btn" %>
          </div>
              <% end %>

            </div>
        </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function () {
  $("#contact_form").validate({
    rules: {
      email: {required: true},
      full_name: {required: true},
      // number: {required: true, phone: true},
      message: {required: true}
    }
  });
});

</script>