config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)

  mount ActionCable.server => '/cable'

  devise_for :users

  resources :tours
	root 'tours#index'

  get '/tours_by_owner', to: 'tours#tours_by_owner', as: 'tours_by_owner'
  delete '/tours/:id/trip_leave/', to: 'tours#trip_leave', as: 'tours_trip_leave'
  post '/tours/subscribe', to: 'tours#subscribe', as: 'tours_subscribe'
  post '/tours/:id/kick', to: 'tours#kick_user', as: 'tour_kick'
  post '/tours/:id/unsubscribe', to: 'tours#unsubscribe', as: 'tours_unsubscribe'
  get '/contest', to: 'tours#contest', as: 'tours_contest'
  post '/new_contest_participant', to: 'tours#new_contest_participant'

  post '/tours/:id/idea', to: 'tours#post_idea', as: 'tours_new_idea'
  delete '/tours/:id/ideas/', to: 'tours#delete_idea', as: 'tours_delete_idea'

  post '/tours/:id/lock', to: 'tours#lock_tour', as: 'tours_lock'
  post '/tours/:id/unlock', to: 'tours#unlock_tour', as: 'tours_unlock'
  get '/contact_us', to: 'static_pages#contactus', as: 'contact_us'
  post '/static_pages/enquiry_contact_details', to: 'static_pages#enquiry_contact_details', as: 'enquiry_contact_details'

end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :category
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :tours_users
  has_many :users, through: :tours_users
  has_many :ideas, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :languages, through: :users
  belongs_to :main_language, class_name: 'Language', foreign_key: 'language_id', optional: true
  has_many :tour_languages, dependent: :destroy

  accepts_nested_attributes_for :tour_languages

  validates_presence_of :name, :description, :owner_id, :start_time, :from_point, :to_point

  has_attached_file :tour_img, styles: {
      thumb: '100x100>',
      mini_img: '350x250>',
      grande_img: '475x325>'
  }, default_url: "/images/missing.jpg"

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :tour_img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :tour_img

  def collected_languages
    result = self.users.includes(:language).map do |user|
      user.language.name
    end
    result << self.owner.language.name
    result.compact.uniq
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe,
                                  :post_idea, :delete_idea, :kick_user, :unlock_tour, :lock_tour]

  before_action :authenticate_user!, except: [:index, :contest, :new_contest_participant]

  # GET /tours
  def index
    @tours = Tour.includes(:owner, :users, :languages).order("created_at DESC")

    if params[:category].blank?
      @tours = @tours.all
    else
      if current_user
        @category_id = Category.find_by(name: params[:category]).id
        @tours = @tours.where(:category_id => @category_id)
      else
        redirect_to new_user_session_path
      end
    end
  end

# GET /tours_by_owner
  def tours_by_owner
    @tours = Tour.includes(:owner,  :users, :languages).where(owner: current_user ).order("created_at DESC").all
   @tourstrip = Tour.includes(:tours_users).where(:tours_users => { :kicked => false,user_id: current_user, :active_subscription => true}).all
    # @tourstrip = Tour.all
  end

  # GET /tours/1
  def show
 # for superuser
  @members = @tour.tours_users.includes(:user).where(kicked: false , active_subscription:true)
#   if current_user.is_superuser == true
#     subscription = current_user.tours_users.where(tour: @tour).first_or_initialize
#     subscription.active_subscription = true
#     subscription.save!
# # for superuser to see all member chat and idea
#     @ideas = @tour.ideas
#     @idea = Idea.new
#     @messages = @tour.messages.includes(:user)
#     @message = Message.new
#     @allowed_user =  current_user == @tour.owner || @tour.tours_users.active.where(user: current_user, kicked: false).first.present?
#   else
    @ideas = @tour.ideas
    @idea = Idea.new
    @messages = @tour.messages.includes(:user)
    @message = Message.new

    @allowed_user =  current_user == @tour.owner || current_user.is_superuser == true || @tour.tours_users.active.where(user: current_user, kicked: false).first.present?
  # end
  end

  # GET /tours/new
  def new
    @tour = Tour.new
    @tour.tour_languages.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
    #@languages= Language.all

  end

  # GET /tours/1/edit
  def edit
    @tour.owner == current_user || not_found
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /tours
  def create
    @tour = Tour.new(tour_params)
    @tour.owner = current_user

    if @tour.save
      redirect_to @tour, notice: 'Tour was successfully created.'
    else
      @categories = Category.all.map{ |c| [c.name, c.id] }
      render :new
    end
  end

  # PATCH/PUT /tours/1
  def update
    @tour.owner == current_user || not_found
    if @tour.update(tour_params)
      redirect_to @tour, notice: 'Tour was successfully updated.'
    else
      @categories = Category.all.map{ |c| [c.name, c.id] }
      render :edit
    end
  end

  # DELETE /tours/1
  def destroy
    @tour.owner == current_user || not_found
    @tour.destroy
    redirect_to tours_url, notice: 'Tour was successfully destroyed.'
  end

  def subscribe
    if @tour.locked?
      redirect_to tour_path(@tour), :flash => { notice: 'This group is locked by the organiser.' }
    elsif current_user.tours_users.active.where(tour: @tour, kicked: false).any?
      redirect_to tour_path(@tour), :flash => { notice: 'You are already subscribed.' }
    elsif current_user.tours_users.active.where(tour: @tour, kicked: true).any?
      redirect_to tour_path(@tour), :flash => { alert: 'The trip owner has limited your access to this page.' }
    else
      subscription = current_user.tours_users.where(tour: @tour).first_or_initialize
      subscription.active_subscription = true
      subscription.save!
      redirect_to tour_path(@tour), :flash => { notice: 'You are subscribed successfully.' }
    end
  end

  def unsubscribe
    @tour = Tour.find(params[:id])
    if @tour.owner==current_user
      user = @tour.tours_users.first.user
      @tour.update(owner: user)
      @tour.tours_users.first.destroy
    end

    subscription = current_user.tours_users.active.where(tour: @tour).first
    if subscription.present?
      subscription.update_attribute(:active_subscription, false)
      redirect_to root_path(@tour), :flash => { notice: 'You are unsubscribed.' }
    else
      redirect_to tour_path(@tour), :flash => { alert: 'You don`t have active subscription to this trip.' }
    end
  end

 def trip_leave
    @tour = Tour.find(params[:id])
    @tour.destroy
    redirect_to root_path, :flash => { notice: 'Your trip is no longer available.' }
 end

  def post_idea
    @tour.owner == current_user || current_user.is_superuser == true || not_found

    text = params.dig(:idea,:text)
    if  text.present? && @tour.ideas.create(text: text)
      redirect_to tour_path(@tour), :flash => { notice: 'An idea is saved.' }
    else
      redirect_to tour_path(@tour), :flash => { alert: 'Input correct idea text.' }
    end
  end

  def delete_idea
    @tour.owner == current_user || not_found

    idea = @tour.ideas.where(id: params[:idea_id]).first

    if idea.present?
      idea.delete
      redirect_to tour_path(@tour), :flash => { notice: 'The idea is deleted.' }
    else
      redirect_to tour_path(@tour), :flash => { alert: 'The idea is not found.' }
    end
  end

  def kick_user
    @tour.owner == current_user || not_found
    subscription = ToursUser.where(tour: @tour, user_id: params[:user_id]).first
    if subscription.present?
      subscription.update_attribute(:kicked, true)
      redirect_to tour_path(@tour), :flash => { notice: 'User is kicked out of this trip.' }
    else
      redirect_to tour_path(@tour), :flash => { alert: 'The user subscription is not found.' }
    end
  end

  def unlock_tour
    @tour.owner == current_user || not_found
    if @tour.update_attribute(:locked, false)
      redirect_to tour_path(@tour), :flash => { notice: 'The tour is unlocked.' }
    else
      redirect_to tour_path(@tour), :flash => { alert: 'A problem has occurred. Try again later.' }
    end
  end

  def lock_tour
    @tour.owner == current_user || not_found
    if @tour.update_attribute(:locked, true)
      redirect_to tour_path(@tour), :flash => { notice: 'The tour is locked.' }
    else
      redirect_to tour_path(@tour), :flash => { alert: 'A problem has occurred. Try again later.' }
    end
  end

  def contest
    @new_participant = ContestParticipant.new
  end

  def new_contest_participant
    @new_participant = ContestParticipant.new(contest_participant_params)
    if @new_participant.valid?
      @new_participant.deliver
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:full_name, :email,:phone_number,:message)
    end
    # Only allow a trusted parameter "white list" through.
    def tour_params
      params.require(:tour).permit(:name, :description, :start_time, :category_id,
                                   :tour_img, :language_id, :from_point, :to_point,
                                   tour_languages_attributes: [:id, :language_id, :_destroy])
    end

    def contest_participant_params
      date_of_birth = "#{params[:contest_participant]['date_of_birth(1i)']}/#{params[:contest_participant]['date_of_birth(2i)']}/#{params[:contest_participant]['date_of_birth(3i)']}"
      params.require(:contest_participant).permit(:first_name, :last_name, :email, :date_of_birth,
                                                  :dream_destinations, :languages, :position,
                                                  :why_to_choose, :friends, :terms_conditions).merge(date_of_birth: date_of_birth.to_date)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_chat.html.erb
<div class="chat-wrap chat-area">
    <h3 class="com-title">Trip <span>Chat</span></h3>
    <div class="chat-block">
        <div class="inner-chat" id="message-table-body" style="max-height: 450px; overflow-y: auto;">
            <% @messages.each do |message| %>
              <%= render partial: 'messages/message', locals: {message: message} %>
            <% end  %>
        </div>
    </div>
</div>



<div id="messages" data-chat-room-id="<%= @tour.id %>"  class="chat-input">
  <%= form_for @message, url: '#', method: :get do |f| %>
      <div class="input-group">
        <%= f.text_area :body, class: 'form-control' %>
        <span class="input-group-btn">
        <%= f.submit "Post", { class: 'fill-btn' } %>
        </span>
      </div>

  <% end %>
</div>

app/views/tours/_contest_participant_form.html.erb
<div class="white-bg pad-block log-wrap">
  <div class="container">
    <%= simple_form_for(new_participant, url: new_contest_participant_path, remote: true) do |f| %>
      <div class="frm-wrap">
        <%= f.error_notification %>
          <div class="gray-box">
            <div class="frm-line">
              <div class="frm-half">
                <div class="form-group">
                  <label> First Name*</label>
                  <%= f.text_field :first_name, class: "form-control", placeholder: "John" %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:first_name)[0] if new_participant.errors[:first_name].present? %></p>
                </div>
              </div>
              <div class="frm-half">
                <div class="form-group">
                  <label> Last Name*</label>
                  <%= f.text_field :last_name, class: "form-control", placeholder: "Smith" %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:last_name)[0] if new_participant.errors[:last_name].present? %></p>
                </div>
              </div>
            </div>
            <div class="frm-line">
              <div class="frm-full">
                <div class="form-group">
                  <label> Email*</label>
                  <%= f.email_field :email, class: "form-control", placeholder: "user@example.com" %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:email)[0] if new_participant.errors[:email].present? %></p>
                </div>
              </div>
            </div>
            <div class="frm-line">
              <div class="frm-half">
                <div class="form-group">
                  <label> Date of birth*</label>
                  <%= f.input :date_of_birth, as: :date, start_year: Date.today.year - 90,
                                  end_year: Date.today.year - 12,
                                  order: [:day, :month, :year], label: false %>

                </div>
              </div>
              <div class="frm-half">
                <div class="form-group">
                  <label> What languages do you speak?* </label>
                  <%= f.text_field :languages, class: 'form-control', placeholder: "French, Japanese, Spanish..." %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:languages)[0] if new_participant.errors[:languages].present? %></p>
                </div>
              </div>
            </div>
            <div class="frm-line">
              <div class="frm-full">
                <div class="form-group">
                  <label>Top 5 Dream Destinations* </label>
                  <%= f.text_field :dream_destinations, autocomplete: "off", class: "form-control", placeholder: "Cities, countries, regions..." %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:dream_destinations)[0] if new_participant.errors[:dream_destinations].present? %></p>

                </div>
              </div>
            </div>
            <div class="frm-line">
              <div class="frm-full">
                <div class="form-group">
                  <label>Where are you from ?* </label>
                  <%= f.text_field :position, autocomplete: "off", class: "form-control", placeholder: "USA, China..." %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:position)[0] if new_participant.errors[:position].present? %></p>

                </div>
              </div>
            </div>
            <div class="frm-line">
              <div class="frm-full">
                <div class="form-group">
                  <label>Why should we chose you?* </label>
                  <%= f.text_area :why_to_choose, autocomplete: "off", class: "form-control bigger-textarea", placeholder: "Tell us everything we should know about you, why you want this job and why you'd be the best at it. Feel free to link us anything that you think might be relevant." %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:why_to_choose)[0] if new_participant.errors[:position].present? %></p>
                </div>
              </div>
            </div>
            <div class="frm-line">
              <div class="frm-full">
                <div class="form-group">
                  <label>If someone you know applied for Dream Life as well and you’d like to go on this adventure with them, tell us who they are.</label>
                  <%= f.text_area :friends, autocomplete: "off", class: "form-control", placeholder: "" %>
                  <p class="error"><%= new_participant.errors.full_messages_for(:friends)[0] if new_participant.errors[:friends].present? %></p>
                </div>
              </div>
            </div>
          </div>
          
          <div class="btn-wrap mar two"><%= f.submit "Send" , { class: 'fill-btn' } %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/tours/_ideas_board.html.erb
<div class="table-responsive tbl-list">
    <table class="table">
      <thead>
      <tr>
        <th>#</th>
        <th>Idea text</th>
        <th colspan="1"></th>
      </tr>
      </thead>
      <tbody>
      <% index = 0 %>
      <% @ideas.each do |idea| %>
          <tr>
            <th scope="row"><%= index += 1 %></th>
            <td><p class="specified"><%= idea.text %></p></td>
            <td class="action"><%= link_to('Delete', tours_delete_idea_path(@tour.id, { idea_id: idea.id }), 'data-confirm' => "Are you sure?", method: :delete, class: 'fill-btn', role: 'button' ) if @tour.owner == current_user %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>

app/views/tours/_members.html.erb
<div class="table-responsive tbl-list">
    <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Joined At</th>
            <th>Status</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row"> 1 </th>
            <td><%= [@tour.owner.First_name,@tour.owner.Last_name.each_char.first].join(' ') %></td>
            <td><%= @tour.created_at.strftime('%H:%M:%S %d %B %Y')  %></td>
            <td><%= 'Active' %></td>
            <td></td>
          </tr>


          <% @members.each_with_index do |link, index| %>
              <tr>
                <th scope="row"><%= index + 2 %></th>
                <td><%= [ link.user.First_name,link.user.Last_name.each_char.first].join(' ') %></td>
                <td><%= link.created_at.strftime('%H:%M:%S %d %B %Y')  %></td>
                <td><%= link.kicked? ? 'Kicked' : 'Active' %></td>

                <td class="action">
                    <%= link_to('Kick', tour_kick_path(@tour.id, { user_id: link.user_id }), 'data-confirm' => "Are you sure?", method: :post, class: 'fill-btn', role: 'button' ) if @tour.owner == current_user && !link.kicked? %>
                </td>

              </tr>

          <% end %>
        </tbody>
    </table>
</div>

app/views/tours/_owner_ideas_board.html.erb
<%= simple_form_for @idea , url: tours_new_idea_path(@tour.id) do |f| %>
    <%= f.input :text, label: 'Post a new idea:', error: 'Idea text is mandatory.' %>
    <%= f.button :submit, { class: 'line-btn' } %>
<% end %>

app/views/tours/_subs_buttons.html.erb
<% if current_user.tours_users.active.where(tour: @tour).first.present? %>
    <% if current_user.tours_users.where(tour: @tour, kicked: true).first.present? %>

    <% else %>
    <%= link_to 'Leave', tours_unsubscribe_path(id: @tour.id), method: :post, class: 'line-btn', role: 'button' %>
    <% end%>
<%else%>
<!-- Hide button form superuser -->
<% if current_user.is_superuser == true%>
<% else%>
    <%= link_to 'Join', "#", class: 'line-btn', role: 'button', id: 'join' %>
    <div id="dialog" style="display: none">
  </div>
<% end %>
<% end%>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <% if @tour.locked? == false %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Voyajers</h4>
      </div>
      <div class="modal-body">
        <p>Welcome to this road trip ! Follow these quick guidelines for the best experience on Voyajers ! </p>
        <p><br>- Talk about it around you !</br> You mignt know someone who knows someone who knows someone... Who craves to go on the same journey ! It'd be sweet to have them join you right and have a common friend with your travel partners.</p>
        <p>- Always meet the people you will travel with beforehand, have a drink with them, get to know them, to be sure that you'll get along all right :)</p>
        <p>- Don't communicate anything personal on this page</p>
        <p>Have Fun :D</p>
      </div>
      <%else%>
      <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p>This Trip is locked by its creator because it's full, create another one for the same destination</p>
        </div>

      <%end%>
      
    <% if @tour.locked? == false %>
      <div class="modal-footer">
        <%= link_to "OK", tours_subscribe_path(id: @tour.id), method: :post ,class: 'line-btn'%>
      </div>
      <%else%>
       <div class="modal-footer">
      <%= link_to "OK", new_tour_path ,class: 'line-btn'%>
      </div>
      <%end%>
    </div>


  </div>
</div>



<!-- <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js" type="text/javascript"></script>
<link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/blitzer/jquery-ui.css"rel="stylesheet" type="text/css" /> -->
<script type="text/javascript">
// for modal popup on join
    $(function () {
        $("#join").click(function (e) {
          e.preventDefault();
            $("#myModal").modal('show');
        });

        $('#myModal').on('hidden', function () {
          document.location.reload();
        })

    });
</script>

app/views/tours/index.html.erb
<% if params[:category].present? %>
<div class="page-head flex-box">
    <div class="inner-head">
        <div class="container">
            <h1 class="head-title"><%= params[:category] %></h1>
            <ol class="breadcrumb">
                <li><%= link_to "Home", root_path%></li>
                <li class="active">Category</li>
            </ol>
        </div>
    </div>
</div>
<% else %>
<div class="banner flex-box">
  <div class="banner-caption">
    <h1 class="banner-title">Create Road Trips or join existing ones</h1>
    <h2 id="sous-titre">The best platform for collaborative Road Trips </p>
  </div>
</div>
<% end %>




<%= render 'tours/tours_index' %>









<script>
$(window).scroll(function() {
    if ($(this).scrollTop() > 1){
        $('header').addClass("sticky");
        $('body').addClass("sticky-b");
    }
    else{
        $('header').removeClass("sticky");
        $('body').removeClass("sticky-b");
    }
});

$( window ).load(function(){
    $(".fix-img").each(function(){

        var img = $(this);
        var image_heightA = img.height();
        var image_widthA = img.width();
        var parent_image_widthA = img.parent().width();
        var parent_image_heightA = img.parent().height();
        //if(width <= height)

        if(image_heightA > parent_image_heightA && image_widthA > parent_image_widthA){

            img.css('width',parent_image_widthA + 'px');
            var tem_image_heightA = img.height();

            if(tem_image_heightA > parent_image_heightA){
                img.css('width','100%');
            }
            else{
                img.css('width','auto');
                img.css('height','100%');
            }
        }
        else{
            img.css('width',parent_image_widthA + 'px');
            var tem_image_heightA = img.height();

            if(tem_image_heightA > parent_image_heightA){
                img.css('width','100%');
            }
            else{
                img.css('width','auto');
                img.css('height','100%');
            }
        }
    });
});

</script>

app/views/tours/new.html.erb
<div class="white-bg pad-block log-wrap">
    <div class="container">
        <div class="main-title">
            <h1>Create <span>Road Trip</span></h1>
        </div>
        <%= render 'form', tour: @tour %>
      </div>
</div>
</div>

app/views/tours/new_contest_participant.js.erb
<% if @new_participant.valid? %>
  $('#successfull-delivery').modal('show')
<% else %>
  $('#new_contest_participant').html('<%= escape_javascript render 'contest_participant_form', new_participant: @new_participant %>');
<% end %>

app/views/tours/show.html.erb
<div class="white-bg pad-block trip-detail">
  <div class="container">
      <div class="row">
          <div class="col-sm-6 col-md-6">
              <div class="trip-image">
                <%= image_tag @tour.tour_img.url(:grande_img), class: "fix-img",alt:"" , style:"width: 100%;" %>
            </div>
            </div>

          <div class="col-sm-6 col-md-6">
              <div class="trip-data">
                  <div class="trip-info">
                  <ins class="bookingaff" data-aid="1288960" data-target_aid="1288592" data-prod="sbp" data-width="500" data-height="130" data-df_num_properties="3">
    <!-- Anything inside will go away once widget is loaded. -->
    <a href="//www.booking.com?aid=1288592">Booking.com</a>
</ins>
<script type="text/javascript">
    (function(d, sc, u) {
      var s = d.createElement(sc), p = d.getElementsByTagName(sc)[0];
      s.type = 'text/javascript';
      s.async = true;
      s.src = u + '?v=' + (+new Date());
      p.parentNode.insertBefore(s,p);
      })(document, 'script', '//aff.bstatic.com/static/affiliate_base/js/flexiproduct.js');
</script>
                      <h3 class="trip-name"><%= @tour.name %></h3>
                      <div class="tag-wrap"><%= @tour.start_time.strftime('%B %Y') %></div>
                      <div class="trip-desc">
                          <p class="desc"><%= @tour.description %></p>
                          <ul>
                              <li><p><strong>Owner:</strong><%= @tour.owner.First_name %> <%= @tour.owner.Last_name.each_char.first %></p></li>
                              <li><p><strong>Start Time:</strong><%= @tour.start_time.strftime('%B %Y') %></p></li>
                              <!-- <li><p><strong>Languages:</strong> <%#= @tour.main_language.try(:name) %></p></li> -->
                              <li><p><strong>Spoken Languages:</strong>
                                <%# @tour.tour_languages.each do |lang| %>
                                  <%#= Language.find(lang.language_id).name %>
                              <%# end %>
                                <%= @tour.tour_languages.map{|p| Language.find(p.language_id).name}.join(",")%>
                            </p></li>
                          </ul>
                          <div>

                        </div>
                      </div>

                      <div class="trip-locat">
                        <p><%= image_tag("pin.png" ,  alt:"") %><%=@tour.category.name %></p>
                        <% if @tour.owner != current_user %>
                            <%= render 'tours/subs_buttons' %>
                        <% else %>
                            <% if @tour.locked? %>
                            <% if @tour.tours_users.count == 0 %>
                              <%= link_to 'Leave', tours_trip_leave_path(id: @tour.id), method: :delete, class: 'line-btn', role: 'button' %>
                            <%else%>
                                <%= link_to 'Leave', tours_unsubscribe_path(id: @tour.id), method: :post, class: 'line-btn', role: 'button' %>
                            <%end%>
                                <%= link_to 'Unlock the Road Trip', tours_unlock_path(@tour), method: :post, class: 'line-btn', role: 'button' %>
                            <% else %>
                            <% if @tour.tours_users.count == 0 %>
                              <%= link_to 'Leave', tours_trip_leave_path(id: @tour.id), method: :delete, class: 'line-btn', role: 'button' %>
                            <%else%>
                                <%= link_to 'Leave', tours_unsubscribe_path(id: @tour.id), method: :post, class: 'line-btn', role: 'button' %>
                            <%end%>
                                <%= link_to 'Lock the Road Trip', tours_lock_path(@tour), method: :post, class: 'line-btn', role: 'button' %>
                            <% end %>
                        <% end %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <hr class="sep" />
      <div class="row">
          <div class="col-md-7">
              <div class="tbl-head">
                  <h3 class="com-title">Road Trip <span>Members</span></h3>

              </div>
              <%= render 'tours/members' %>
              <% if @allowed_user %>
                  <div class="tbl-head">
                      <h3 class="com-title">Idea <span>Board</span></h3>
                  </div>
                  <%= render 'tours/ideas_board' %>
                  <% if @tour.owner == current_user || current_user.is_superuser == true %>
                      <%= render 'tours/owner_ideas_board' %>
                  <% end %>
                <% end %>
              </div>
              <% if @allowed_user || current_user.is_superuser == true %>
                <div class="col-md-5">
                    <%= render 'tours/chat' %>
                </div>
              <% end %>
      </div>
  </div>
</div>


<script>
$(window).scroll(function() {
	if ($(this).scrollTop() > 1){
		$('header').addClass("sticky");
		$('body').addClass("sticky-b");
	}
	else{
		$('header').removeClass("sticky");
		$('body').removeClass("sticky-b");
	}
});

$( window ).load(function(){
    $(".fix-img").each(function(){

        var img = $(this);
        var image_heightA = img.height();
        var image_widthA = img.width();
        var parent_image_widthA = img.parent().width();
        var parent_image_heightA = img.parent().height();
        //if(width <= height)

        if(image_heightA > parent_image_heightA && image_widthA > parent_image_widthA){

            img.css('width',parent_image_widthA + 'px');
            var tem_image_heightA = img.height();

            if(tem_image_heightA > parent_image_heightA){
                img.css('width','100%');
            }
            else{
                img.css('width','auto');
                img.css('height','100%');
            }
        }
        else{
            img.css('width',parent_image_widthA + 'px');
            var tem_image_heightA = img.height();

            if(tem_image_heightA > parent_image_heightA){
                img.css('width','100%');
            }
            else{
                img.css('width','auto');
                img.css('height','100%');
            }
        }
    });
});

</script>

app/views/tours/tours_by_owner.html.erb
<%= render 'tours/tours_index' %>