config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)

  mount ActionCable.server => '/cable'

  devise_for :users

  resources :tours
	root 'tours#index'

  get '/tours_by_owner', to: 'tours#tours_by_owner', as: 'tours_by_owner'
  delete '/tours/:id/trip_leave/', to: 'tours#trip_leave', as: 'tours_trip_leave'
  post '/tours/subscribe', to: 'tours#subscribe', as: 'tours_subscribe'
  post '/tours/:id/kick', to: 'tours#kick_user', as: 'tour_kick'
  post '/tours/:id/unsubscribe', to: 'tours#unsubscribe', as: 'tours_unsubscribe'
  get '/contest', to: 'tours#contest', as: 'tours_contest'
  post '/new_contest_participant', to: 'tours#new_contest_participant'

  post '/tours/:id/idea', to: 'tours#post_idea', as: 'tours_new_idea'
  delete '/tours/:id/ideas/', to: 'tours#delete_idea', as: 'tours_delete_idea'

  post '/tours/:id/lock', to: 'tours#lock_tour', as: 'tours_lock'
  post '/tours/:id/unlock', to: 'tours#unlock_tour', as: 'tours_unlock'
  get '/contact_us', to: 'static_pages#contactus', as: 'contact_us'
  post '/static_pages/enquiry_contact_details', to: 'static_pages#enquiry_contact_details', as: 'enquiry_contact_details'

end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
      <div class="foot-logo">
        <%= link_to root_path  ,class:"navbar-brand" do %>
        <%= image_tag("foot-logo.png" , alt:"")  %>
        <% end %>
      </div>
      <div class="copy">
        <h3 align="right"><%= link_to "Contact Us", contact_us_path %></h3>
        <p>Copyrights © Voyajers, All Rights Reserved.</p><br>

      </div>
    </div>
</footer>

<script type="text/javascript">
  $("#btn-concours").click(function() {
   $('html,body').animate({
     scrollTop: $("#suite").offset().top - 35
    },
    'slow');
  });

  $("#btn-concours-suite").click(function() {
   $('html,body').animate({
     scrollTop: $("#text-model").offset().top + 15
    },
    'slow');
  });

  $("#btn-concours-form").click(function() {
   $('html,body').animate({
     scrollTop: $("#form").offset().top + 5
    },
    'slow');
  });
</script>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <%= link_to root_path  ,class:"navbar-brand" do %>
          <%= image_tag("logo.png" , alt:"")  %>
          <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">



            <li class ="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% Category.all.each do |category| %>
                    <li class="<%= 'active' if params[:category] == category.name %>">
                      <%= link_to category.name, tours_path(category: category.name), class: "link" %>
                    </li>
                <% end %>
              </ul>
            </li>
              <% if user_signed_in? %>
                  <li><%= link_to "Create Road Trip", new_tour_path %></li>
                  <li><%= link_to "My Road Trips", tours_by_owner_path %></li>
                  <li><%= link_to "Contact Us", contact_us_path %></li>
                  <li class = 'contest-tab'><%= link_to "Dream Life", tours_contest_path %></li>
                  <li class ="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                    </ul>
                  </li>
              <% else %>
                  <li><%= link_to "Contact Us", contact_us_path %></li>
                  <li><%= link_to "Sign Up", new_user_registration_path %></li>
                  <li><%= link_to "Log In", new_user_session_path %></li>
                  <li class = 'contest-tab'><%= link_to "Dream Life", tours_contest_path %></li>
              <% end %>
          </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voyajers | Road Trips </title>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/header' %>
  <% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
  <% end %>
  <% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>


</body>
</html>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>